// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzmgn07hx9sxjRj2v6KGpszjQxR2qtbgg',
    appId: '1:999894490491:web:4046be94ea062df1aeb1de',
    messagingSenderId: '999894490491',
    projectId: 'gamebooking-d0fe5',
    authDomain: 'gamebooking-d0fe5.firebaseapp.com',
    storageBucket: 'gamebooking-d0fe5.firebasestorage.app',
    measurementId: 'G-7VG5Y3N23H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzxXA1H7D6p7C9NXeycOvnArQp_Np0gcU',
    appId: '1:999894490491:android:357886db5c7b2852aeb1de',
    messagingSenderId: '999894490491',
    projectId: 'gamebooking-d0fe5',
    storageBucket: 'gamebooking-d0fe5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZW7yDMG3KUSnbNSGHj_-noC1JTMzv5k',
    appId: '1:999894490491:ios:ad52e17f9c56fbe9aeb1de',
    messagingSenderId: '999894490491',
    projectId: 'gamebooking-d0fe5',
    storageBucket: 'gamebooking-d0fe5.firebasestorage.app',
    iosBundleId: 'com.example.slotbooking',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsZW7yDMG3KUSnbNSGHj_-noC1JTMzv5k',
    appId: '1:999894490491:ios:ad52e17f9c56fbe9aeb1de',
    messagingSenderId: '999894490491',
    projectId: 'gamebooking-d0fe5',
    storageBucket: 'gamebooking-d0fe5.firebasestorage.app',
    iosBundleId: 'com.example.slotbooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzmgn07hx9sxjRj2v6KGpszjQxR2qtbgg',
    appId: '1:999894490491:web:807643b82c547d6daeb1de',
    messagingSenderId: '999894490491',
    projectId: 'gamebooking-d0fe5',
    authDomain: 'gamebooking-d0fe5.firebaseapp.com',
    storageBucket: 'gamebooking-d0fe5.firebasestorage.app',
    measurementId: 'G-204X11M43Z',
  );
}
